//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnoViewer_WebForms.Samples
{


    public partial class Multiple
    {

        /// <summary>
        /// ctlUnoOne control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Uno.Files.Viewer.UnoViewer ctlUnoOne;

        /// <summary>
        /// ctlUnoTwo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Uno.Files.Viewer.UnoViewer ctlUnoTwo;
    }
}
